baseURL = 'https://ryleighdavis.github.io'
languageCode = 'en-us'
title = 'Ryleigh Davis'
theme = 'hugo-theme-cleanwhite'

# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true

[pagination]
  pagerSize = 5 #frontpage pagination

hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "img/europa.jpeg"
  SEOTitle = "Ryleigh Davis, Planetary Scientist"
  description = "Personal & Professional website of Ryleigh Davis, Planetary Scientist."
  keyword = "Ryleigh Davis, Planetary Science, Astronomy, Caltech, Solar System, Europa, Callisto, JWST"
  slogan = "Planetary Science Ph.D. Candidate"
  upstreamAttribution = true

  image_404 = "img/404-bg.jpg"
  title_404 = "Page Not Found :("
  omit_categories = false

  # leancloud storage for page view counter
  page_view_conter = false 
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  #sidebar_about_description = "Planetary Scientist, TODO_SIDEBAR!"
  #sidebar_avatar = "img/avatar-zhaohuabing.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  #sidebar_avatar = "img/zhaohuabing.png"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = false 
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  # Twikoo comments
  # Follow https://twikoo.js.org/ to set up your own env_id
  twikoo_env_id = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = false 
  # reward_guide = "如果这篇文章对你有用,请随意打赏" 

  friends = false
  bookmarks = false
  about_me = true

  # Include any custom CSS and/or JS files, url or relative to /static folder
  custom_css = ["css/mobile-responsive.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.social]
  rss            = false 
  email          = "rdavis@caltech.edu"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  twitter        = "https://twitter.com/import_astrory"
  linkedin       = "https://www.linkedin.com/in/m-ryleigh-davis-5186377b/"
  #stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/RyleighDavis"
  #wechat         = "your wechat qr code image"
  #medium        = "full profile url in medium"
  #slack         = "full workspace url in slack"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"
  
  [[params.friend_link]]
  title = "Example Friend"
  href =  "https://examplefriend.com"

  [[params.bookmark_link]]
  title =  "Martin Fowler"
  href =  "https://martinfowler.com"
  [[params.bookmark_link]]
  title = "ServiceMesher"
  href =  "http://www.servicemesher.com"
  [[params.bookmark_link]]
  title =  "Pxhere"
  href = "https://pxhere.com"
  [[params.bookmark_link]]
  title = "unsplash"
  href = "https://unsplash.com"
  
  [[params.addtional_menus]]
  title =  "Research"
  href =  "/research/"
  [[params.addtional_menus]]
  title =  "Publications"
  href =  "/publications/"
  [[params.addtional_menus]]
  title =  "CV"
  href =  "/cv.pdf"
  [[params.addtional_menus]]
  title =  "About"
  href =  "/about/"
  [[params.addtional_menus]]
  title =  "Contact"
  href =  "/contact/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.parser.attribute]
    block = true
